'use strict';

// ── SECTION CONTENT ───────────────────────────────────────────────────────────
// Edit these arrays with real content for each section
const SECTION_CONTENT = {
  ART: [
    ['bright', '[ ART ]'],
    ['dim',    '─'.repeat(36)],
    null,
    ['dim',    '> ls ~/art/'],
    ['ok',     '  paintings/   digital/   photography/'],
    null,
    ['dim',    '> cat about.txt'],
    ['',       'Visual work exploring systems, noise,'],
    ['',       'and the space between signal and static.'],
    null,
    {type:'bar', label:'[*] loading:    ', steps:10, delay:80, done:'READY', doneCls:'ok'},
    ['bright', '  — gallery coming soon —'],
  ],
  GAMES: [
    ['bright', '[ GAMES ]'],
    ['dim',    '─'.repeat(36)],
    null,
    ['dim',    '> ls ~/games/'],
    ['ok',     '  project-alpha/    [IN DEV]'],
    ['ok',     '  void-crawler/     [SHIPPED]'],
    ['ok',     '  neon-tactics/     [SHIPPED]'],
    null,
    ['dim',    '> cat status.log'],
    ['',       '2 shipped  ·  1 in development'],
    ['',       'Platform: web, desktop'],
    null,
    {type:'bar', label:'[*] loading:    ', steps:10, delay:80, done:'READY', doneCls:'ok'},
    ['bright', '  — projects coming soon —'],
  ],
  MUSIC: [
    ['bright', '[ MUSIC ]'],
    ['dim',    '─'.repeat(36)],
    null,
    ['dim',    '> ls ~/audio/'],
    ['ok',     '  tracks/   releases/   collabs/'],
    null,
    ['dim',    '> aplay --info'],
    ['',       '47 tracks  ·  4 EPs  ·  1 LP'],
    ['',       'ambient / electronic / experimental'],
    null,
    {type:'bar', label:'[*] loading:    ', steps:10, delay:80, done:'READY', doneCls:'ok'},
    ['bright', '  — listen coming soon —'],
  ],
  WORK: [
    ['bright', '[ WORK ]'],
    ['dim',    '─'.repeat(36)],
    null,
    ['dim',    '> cat skills.txt'],
    ['',       '  Design     ████████░░'],
    ['',       '  Dev        ██████████'],
    ['',       '  Audio      ███████░░░'],
    null,
    ['dim',    '> ls ~/work/clients/'],
    ['ok',     '  [redacted]/   [redacted]/   [redacted]/'],
    null,
    {type:'bar', label:'[*] loading:    ', steps:10, delay:80, done:'READY', doneCls:'ok'},
    ['bright', '  — portfolio coming soon —'],
  ],
  WRITING: [
    ['bright', '[ WRITING ]'],
    ['dim',    '─'.repeat(36)],
    null,
    ['dim',    '> ls ~/writing/'],
    ['ok',     '  essays/   fiction/   notes/'],
    null,
    ['dim',    '> wc -w **/*.md'],
    ['',       '  ~47,000 words and counting'],
    null,
    {type:'bar', label:'[*] loading:    ', steps:10, delay:80, done:'READY', doneCls:'ok'},
    ['bright', '  — archive coming soon —'],
  ],
};
